[package]
name = "xplm"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
xplm-sys = { git = "https://github.com/artemkorobko/xplm-sys.git" }

[patch."https://github.com/artemkorobko/xplm-sys.git"]
xplm-sys = { path = "../xplm-sys" }
